# Generated by Django 5.1.1 on 2024-09-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('description_text', models.CharField(max_length=200)),
                ('status_text', models.CharField(default='Pendente', max_length=200)),
                ('userAssign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAssign', to='users.user')),
                ('userMaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMaker', to='users.user')),
            ],
        ),
    ]
